### ISSUE TITLE
Add links to more advanced resources

### ISSUE THREAD

**Issue by lysnikolaou** [Quansight-Labs/free-threaded-compatibility#100]
It'd probably be helpful to add links to more advanced resources. Not sure what the correct place is, but I'll take a stab at it soon.

Should probably include (at least) the following:

- [CPython internal docs](https://github.com/python/cpython/tree/main/InternalDocs)
- [Sam's EuroPython talk](https://www.youtube.com/watch?v=9OOJcTp8dqE)
- [Nathan's comment on the NumPy tracker](https://github.com/numpy/numpy/pull/26693#issuecomment-2179649117)

**Comment by ngoldbaum** [comment]
We added this in #102.
