### ISSUE TITLE
Status of SciPy compatibility

### ISSUE THREAD

**Issue by andfoy** [Quansight-Labs/free-threaded-compatibility#12]
SciPy issue tracker: https://github.com/scipy/scipy/issues/20669

**Comment by rgommers** [comment]
Status update:
- Test suite passing (disclaimer: with known thread-safety issues not covered by tests),
- Nightly Linux wheels available at https://anaconda.org/scientific-python-nightly-wheels/scipy as of today.

**Comment by rgommers** [comment]
macOS nightly wheels are also available now at https://anaconda.org/scientific-python-nightly-wheels/scipy

**Comment by lysnikolaou** [comment]
Closing in favor of the upstream issue.
