### ISSUE TITLE
Status of pybind11 compatibility

### ISSUE THREAD

**Issue by ngoldbaum** [Quansight-Labs/free-threaded-compatibility#13]
Tracking issue: https://github.com/pybind/pybind11/issues/5112

**Comment by henryiii** [comment]
- Compile in free threading but leave GIL on: https://github.com/pybind/pybind11/pull/5139
- Compile in free threading and pass tests (2 remaining)
- Support free threading with API and locks: TODO (waiting on #6)

**Comment by colesbury** [comment]
PR:
* https://github.com/pybind/pybind11/pull/5148

**Comment by henryiii** [comment]
2.13 released!

**Comment by rgommers** [comment]
Awesome 🎉. 

Re the second bullet above on locking:  since `PyMutex` just became public, using that for lower-overhead locking is probably a future enhancement for Pybind11?
