### ISSUE TITLE
Status of joblib compatibility

### ISSUE THREAD

**Issue by lesteve** [Quansight-Labs/free-threaded-compatibility#22]
Joblib tracking issue: https://github.com/joblib/joblib/issues/1592

I opened this mostly for visibility, hopefully this is OK :wink:

**Comment by rgommers** [comment]
Yeah no worries at all, thanks @lesteve! Maybe at some point it's time to build a nicer overview table (e.g., like https://python3statement.github.io/), but for now one issue per package, group of related packages, or topic seems great.

**Comment by rgommers** [comment]
@lesteve we're deploying the website suggested above (see gh-25). It looks like all changes in `joblib` were adding CI and fixing up tests. Given that there were no code changes in `joblib` needed, can we list 1.4.2 as compatible?

**Comment by lesteve** [comment]
> can we list 1.4.2 as compatible?

I think so, there is https://github.com/joblib/joblib/pull/1594 that I need to take closer look at but that's when you changed the default joblib backend to be threading, which is not really something a user would do.
