### ISSUE TITLE
Status of PyO3 support

### ISSUE THREAD

**Issue by ngoldbaum** [Quansight-Labs/free-threaded-compatibility#53]
Tracking issue: https://github.com/PyO3/pyo3/issues/4265

Currently building PyO3 against a free-threaded Python build requires setting `UNSAFE_PYO3_BUILD_FREE_THREADED=1`. Right now it's not worth doing that unless you're working on free-threaded support in PyO3 since it will segfault or deadlock in many situations.

Myself and @davidhewitt are going to have a standing meeting on Fridays to discuss work on PyO3 free-threaded support and I'm ramping up on the PyO3 codebase.

**Comment by lysnikolaou** [comment]
Closing in favor of the upstream issue.
