### ISSUE TITLE
Status of cffi compatibility

### ISSUE THREAD

**Issue by minrk** [Quansight-Labs/free-threaded-compatibility#54]
Tracking issue for `cffi` is here: https://github.com/python-cffi/cffi/issues/40

**Comment by rgommers** [comment]
Thanks @minrk. Let me also copy over the relevant part of [your original comment](https://github.com/Quansight-Labs/free-threaded-compatibility/issues/7#issuecomment-2263031136):

_I was testing Jupyter today, and of the extension dependencies for JupyterLab, these appear to both be limiting factors. Most extensions are working fine, though:_

- _`argon-cffi-bindings` uses `cffi` which unconditionally sets the unsupported `py_limited_api=True` (I got this to build with https://github.com/python-cffi/cffi/pull/104)_

_so I can run a nogil kernel, but not the UI yet._

**Comment by lysnikolaou** [comment]
Closing in favor of the upstream issue.
